# Site settings
title: NHibernate Forge
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "http://nhibernate.github.io"
twitter_username: nhibernate
github_username:  nhibernate

# Build settings
markdown: kramdown
